version: "2"
services:
  app:
    build: .
    entrypoint: ./entrypoint/app.sh
    links:
      - db
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/AuthManager

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: apnaschoolmysqldb
  redis:
    image: redis:latest

  worker:
    build:
      context: .
    command: celery -A app.celery worker --loglevel=info
